# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import event_pb2 as event__pb2
import grpc

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in event_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEventAll = channel.unary_unary(
            "/event.EventService/GetEventAll",
            request_serializer=event__pb2.Request.SerializeToString,
            response_deserializer=event__pb2.Response.FromString,
            _registered_method=True,
        )
        self.GetEvent = channel.unary_unary(
            "/event.EventService/GetEvent",
            request_serializer=event__pb2.Request.SerializeToString,
            response_deserializer=event__pb2.Response.FromString,
            _registered_method=True,
        )
        self.GetEventById = channel.unary_unary(
            "/event.EventService/GetEventById",
            request_serializer=event__pb2.RequestById.SerializeToString,
            response_deserializer=event__pb2.Response.FromString,
            _registered_method=True,
        )
        self.EventCheckTime = channel.unary_unary(
            "/event.EventService/EventCheckTime",
            request_serializer=event__pb2.RequestById.SerializeToString,
            response_deserializer=event__pb2.ResponseCheck.FromString,
            _registered_method=True,
        )


class EventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEventAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEventById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EventCheckTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetEventAll": grpc.unary_unary_rpc_method_handler(
            servicer.GetEventAll,
            request_deserializer=event__pb2.Request.FromString,
            response_serializer=event__pb2.Response.SerializeToString,
        ),
        "GetEvent": grpc.unary_unary_rpc_method_handler(
            servicer.GetEvent,
            request_deserializer=event__pb2.Request.FromString,
            response_serializer=event__pb2.Response.SerializeToString,
        ),
        "GetEventById": grpc.unary_unary_rpc_method_handler(
            servicer.GetEventById,
            request_deserializer=event__pb2.RequestById.FromString,
            response_serializer=event__pb2.Response.SerializeToString,
        ),
        "EventCheckTime": grpc.unary_unary_rpc_method_handler(
            servicer.EventCheckTime,
            request_deserializer=event__pb2.RequestById.FromString,
            response_serializer=event__pb2.ResponseCheck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "event.EventService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("event.EventService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEventAll(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event.EventService/GetEventAll",
            event__pb2.Request.SerializeToString,
            event__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event.EventService/GetEvent",
            event__pb2.Request.SerializeToString,
            event__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEventById(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event.EventService/GetEventById",
            event__pb2.RequestById.SerializeToString,
            event__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EventCheckTime(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event.EventService/EventCheckTime",
            event__pb2.RequestById.SerializeToString,
            event__pb2.ResponseCheck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
